# permissions for end users to view cephclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ceph-csi-operator
    app.kubernetes.io/managed-by: kustomize
  name: cephcluster-viewer-role
rules:
- apiGroups:
  - csi.ceph.io
  resources:
  - cephclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csi.ceph.io
  resources:
  - cephclusters/status
  verbs:
  - get
