
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nfs-ctrlplugin-crb 
subjects:
  - kind: ServiceAccount
    name: csi-nfs-ctrlplugin-sa 
    namespace: system 
roleRef:
  kind: ClusterRole
  name: csi-nfs-ctrlplugin-cr 
  apiGroup: rbac.authorization.k8s.io
