apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    olm.skipRange: ""
    operators.operatorframework.io/operator-type: non-standalone
  name: cephcsi-operator.v0.1.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  description: Operator to deploy ceph csi drivers.
  displayName: CephCSI operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - storage
  - csi
  links:
  - name: Github Repo
    url: https://github.com/ceph/ceph-csi-operator
  maintainers:
  - email: ceph-csi-team@redhat.com
    name: CephCSI Community
  maturity: alpha
  provider:
    name: CephCSI Community
  version: 0.1.1
  replaces: ""
