## Append samples of your project ##
resources:
- csi_v1alpha1_driver.yaml
- csi_v1alpha1_operatorconfig.yaml
- csi_v1alpha1_cephcluster.yaml
- csi_v1alpha1_config.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
