name: Publish Helm Charts to GitHub Pages

on:
  release:
    types: [published]

jobs:
  release:
    name: Package and Release Helm Charts
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install chart-releaser
        run: |
          echo "Installing chart-releaser..."
          curl -sSL https://github.com/helm/chart-releaser/releases/download/v1.5.0/cr-linux-amd64 -o cr
          chmod +x cr
          sudo mv cr /usr/local/bin/cr
          echo "chart-releaser installed."
 
      - name: Package Helm charts
        run: |
          echo "Packaging Helm charts..."
          mkdir -p .csi-op-release-packages
          echo "Packaging Helm charts for csi-operator..."
          ls -lrt
          helm package deploy/charts/ceph-csi-operator -d .csi-op-release-packages
          echo "Packaging Helm charts for csi-driver..."
          helm package deploy/charts/ceph-csi-drivers -d .csi-op-release-packages

      - name: Upload chart packages to GitHub Releases
        run: |
          echo "uploading the package to the release"
          cr upload \
            --owner=${{ github.repository_owner }} \
            --repo=${{ github.repository }} \
            --package-path=.csi-op-release-packages

      - name: Update Helm repo index and push to gh-pages
        run: |
          echo "pushing it to the github pacges"
          mkdir -p .cr-index
          cr index \
            --owner=${{ github.repository_owner }} \
            --repo=${{ github.repository }} \
            --package-path=.csi-op-release-packages \
            --index-path=.cr-index/index.yaml \
            --charts-repo=https://${{ github.repository_owner }}.github.io/${{ github.repository }}/

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          echo "Checking if gh-pages branch exists..."
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          echo "If gh-pages branch didn't exist, it has been created."
          cp -r .cr-index/* .
          git add .
          git commit -m "Update Helm repo index from release ${{ github.event.release.tag_name }}"
          git push origin gh-pages
          


