name: Publish Helm Charts to GitHub Pages

on:
  release:
    types: [published]

jobs:
  release:
    name: Package and Release Helm Charts
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    env:
      CR_TOKEN: ${{ secrets.CSI_GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Install and use chart-releaser-action
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts-dir: "deploy/charts"
          cr-token: ${{ secrets.MY_GITHUB_TOKEN }}
          version: ${{ github.event.release.tag_name }}

      - name: Update Helm repo index and push to gh-pages
        run: |
          echo "Configuring Git..."
          git config --global user.email "madhupr007@gmail.com"
          git config --global user.name "Madhu Rajanna"

          echo "Fetching gh-pages branch..."
          git fetch origin gh-pages
          git checkout gh-pages

          echo "Committing changes..."
          git add .
          git commit -m "Update Helm repo index from release ${{ github.event.release.tag_name }}"
          git push origin gh-pages
          echo "Push complete."
